export const developmentTeam = [
  "Alison Walden",
  "Alan Evanson",
  "Alison Hall",
  "Brian Elton",
  "David Jackson",
  "Diego Escobar",
  "Dustin Sampson",
  "Gregory Smith",
  "Joel Brown",
  "Jonathan Rodness",
  "Kristen Nakamura",
  "Lisa Kuliczkowski",
  "Michael Simla",
  "Mike Quattrin",
  "Natasha Johnston",
  "Noel Tibbles",
  "Pauline Ramos",
  "Puneet Seghal",
  "Rene Noel",
  "Suvi Vignarajah",
  "Tolu Adegbite",
  "Wesley Cocks",
  "Yi Wang",
  "Zoltan Hawryluk"
];
